'''Stacking meta-learner over pairwise P4 (ViTPose / easy ViTPose) ST-GCN outputs.

Inference uses **ViTPose** ``.npy`` clips only (same pipeline as ``run_p4_pairwise.py``),
not DeepLabCut HDF5. Pass ``--config model_training_v2/config_p4_pairwise.yaml``.

This script trains a meta-classifier from OvO pairwise probabilities
P(class_pos|clip) generated by pre-trained binary ST-GCN models (typically
C(10,2)=45 directories; use ``--min-best-epoch`` to subset). By default the
target is **10-way** ``audio_label_10``. With ``--meta-binary-pain`` the target
is binary (pain vs non-pain) using ``labels.binary_pain_class``, with the same
pairwise probability features.

Optional: ``--min-best-epoch`` drops pairwise runs whose ``training/run_summary.json``
reports an early best checkpoint (0-based ``best_epoch``), which often correlates
with degenerate / collapsed training in hparam sweeps.

Optional: ``--pain-pair-models-only`` keeps only binary models whose ``pair_meta`` includes
``labels.binary_pain_class`` (typically 9 pairwise features from 45 for 10 classes). Unless
``--meta-binary-pain`` is set, the meta target remains **10-way** ``audio_label_10``.

Example (full grid, meta-train grouped CV, drop early-best base checkpoints, optional pain-only features):

  python -m model_training_v2.scripts.train_stgcn_dlc_stack \\
    --config model_training_v2/config_p4_pairwise.yaml \\
    --holdout-manifest path/to/holdout_manifest_audio10.jsonl \\
    --model-dirs-json path/to/stack_model_dirs_45.json \\
    --audio-confidence-filter 0.65 \\
    --cv-splits 3 \\
    --min-best-epoch 10 \\
    --pain-pair-models-only

Binary meta target (10-class labels collapsed to pain vs rest):

  ... same flags ... --meta-binary-pain

Why stacking on pairwise outputs
- The binary pairwise outputs preserve class boundaries from sub-problems.
- The meta stage learns cross-pair arbitration and calibration across all classes.

Why held-out data only
- Base binary models must not have seen these clips. Otherwise the meta-learner
  can overfit to correlated sub-model errors and produce overly optimistic
  estimates.

Why class_weight='balanced'
- Subclass frequencies are not uniform; weighting counters dominant class bias in
  the meta objective.

Why top-3 accuracy
- With 10 classes, top-1 can be too strict for operational triage. A
  top-3 metric captures useful rank-based performance.
'''

from __future__ import annotations

import os
import sys

# macOS: multiple OpenMP runtimes (XGBoost, Accelerate/OpenBLAS, joblib/loky) frequently
# segfault unless thread pools are pinned to 1 *before* numpy/torch/xgboost load.
if sys.platform == 'darwin':
    for _k, _v in (
        ('OMP_NUM_THREADS', '1'),
        ('OPENBLAS_NUM_THREADS', '1'),
        ('MKL_NUM_THREADS', '1'),
        ('VECLIB_MAXIMUM_THREADS', '1'),
        ('NUMEXPR_NUM_THREADS', '1'),
    ):
        os.environ.setdefault(_k, _v)

import argparse
import copy
import json
import logging
from collections import Counter
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parents[3]
_POSE_MODELS = _REPO / "video" / "pose-models"
for _p in (_REPO, _POSE_MODELS):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    top_k_accuracy_score,
)
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import StratifiedGroupKFold, StratifiedKFold
from sklearn.utils.class_weight import compute_class_weight, compute_sample_weight

# RF/KNN use joblib threads; on macOS keep single-threaded next to XGBoost/libomp.
_META_RF_KNN_N_JOBS = 1 if sys.platform == 'darwin' else -1

from class_subset_utils import  first_stratified_group_split
from data_loading import  (
    REPO_ROOT,
    _to_repo_relative,
    get_multiclass_class_names,
    load_pose_extraction_index,
    pose_file_exists,
    resolve_v1_pose,
)
from data_engineering import  PoseDataset
from models.p4_pose_stgcn import  P4PoseSTGCN
from torch.nn import functional as F
from torch.utils.data import DataLoader

try:
    from tqdm.auto import tqdm
except Exception:
    def tqdm(iterable, *args, **kwargs):  # pragma: no cover - fallback when tqdm missing
        return iterable

try:
    from xgboost import XGBClassifier

    HAS_XGB = True
    _XGB_IMPORT_ERR: str | None = None
except Exception as e:
    XGBClassifier = None  # type: ignore
    HAS_XGB = False
    _XGB_IMPORT_ERR = f'{type(e).__name__}: {e}'

try:
    from lightgbm import LGBMClassifier

    HAS_LGBM = True
    _LGBM_IMPORT_ERR: str | None = None
except Exception as e:
    LGBMClassifier = None  # type: ignore
    HAS_LGBM = False
    _LGBM_IMPORT_ERR = f'{type(e).__name__}: {e}'


def configure_logger(run_root: Path) -> logging.Logger:
    logger = logging.getLogger('train_stgcn_dlc_stack')
    logger.setLevel(logging.INFO)
    logger.propagate = False
    logger.handlers = []
    fmt = logging.Formatter('%(asctime)s | %(levelname)s | %(message)s')
    fh = logging.FileHandler(run_root / 'train.log', mode='a')
    sh = logging.StreamHandler()
    fh.setFormatter(fmt)
    sh.setFormatter(fmt)
    fh.setLevel(logging.INFO)
    sh.setLevel(logging.INFO)
    logger.addHandler(fh)
    logger.addHandler(sh)
    return logger


def log_section(logger: logging.Logger, title: str) -> None:
    logger.info('')
    logger.info('%s %s', '=' * 4, title)
    logger.info('-' * 60)


def load_config(path: Path) -> dict[str, Any]:
    import yaml

    with open(path, 'r') as f:
        return yaml.safe_load(f)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Train stacking meta-learner on 45 P4 ViTPose pairwise checkpoints (no DeepLabCut).'
    )
    parser.add_argument(
        '--config',
        type=Path,
        required=True,
        help='P4 / ViTPose yaml (e.g. model_training_v2/config_p4_pairwise.yaml)',
    )
    parser.add_argument('--holdout-manifest', required=True)
    parser.add_argument('--model-dirs', action='append', default=[])
    parser.add_argument('--model-dirs-json', default=None)
    parser.add_argument('--audio-confidence-filter', type=float, default=None)
    parser.add_argument('--batch-size', type=int, default=32)
    parser.add_argument('--limit', type=int, default=None)
    parser.add_argument('--split-fraction', type=float, default=0.333)
    parser.add_argument('--random-seed', type=int, default=42)
    parser.add_argument(
        '--cv-splits',
        type=int,
        default=1,
        metavar='N',
        help='If N>1, run N-fold grouped stratified CV on meta-train only (group=cat_id); '
        'log mean±std macro-F1 / top-3 / AUC; final fit still uses full meta-train; holdout metrics unchanged.',
    )
    parser.add_argument(
        '--min-best-epoch',
        type=int,
        default=None,
        metavar='E',
        help='If set, drop model dirs with training/run_summary.json best_epoch < E '
        '(0-based, same field as training_loop). Example: 10 removes early-best pairs.',
    )
    parser.add_argument(
        '--pain-pair-models-only',
        action='store_true',
        help='After resolving 45 dirs, keep only pair_meta dirs involving labels.binary_pain_class '
        '(typically 9 pairwise pain models). Unless --meta-binary-pain, meta target stays 10-way; '
        'binary pain vs non-pain metrics are always logged on meta-val when pain class is in label set.',
    )
    parser.add_argument(
        '--meta-binary-pain',
        action='store_true',
        help='Train/validate the meta-learner on binary pain vs non-pain only '
        '(y=1 iff audio_label_10 == labels.binary_pain_class). Still uses the same pairwise probability features.',
    )
    parser.add_argument('--dry-run', action='store_true')
    return parser.parse_args()


def get_run_root() -> Path:
    ts = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')
    root = Path('video/pose-models/runs') / f'stgcn_dlc_stack_{ts}'
    root.mkdir(parents=True, exist_ok=True)
    return root


def parse_model_dirs(args: argparse.Namespace) -> list[Path]:
    dirs = [Path(x).expanduser().resolve() for x in args.model_dirs]
    if args.model_dirs_json:
        with open(args.model_dirs_json, 'r') as f:
            json_dirs = json.load(f)
        if not isinstance(json_dirs, list):
            raise ValueError('--model-dirs-json must be a JSON list')
        dirs.extend([Path(x).expanduser().resolve() for x in json_dirs])
    dirs = list(dict.fromkeys(dirs))
    if len(dirs) != 45:
        raise ValueError(f'Expected 45 model directories, got {len(dirs)}')
    return sorted(dirs)


def load_pair_meta(model_dir: Path) -> dict[str, Any]:
    p = model_dir / 'pair_meta.json'
    if not p.exists():
        raise FileNotFoundError(f'missing pair_meta.json: {p}')
    with open(p, 'r') as f:
        return json.load(f)


def read_training_best_epoch(model_dir: Path) -> int | None:
    train = model_dir / 'training'
    for name in ('run_summary.json', 'fold_summary.json'):
        p = train / name
        if not p.is_file():
            continue
        try:
            with open(p, encoding='utf-8') as f:
                d = json.load(f)
        except json.JSONDecodeError:
            continue
        be = d.get('best_epoch')
        if be is not None:
            return int(be)
    return None


def filter_model_dirs_by_min_best_epoch(
    model_dirs: list[Path],
    min_best_epoch: int,
    logger: logging.Logger,
) -> tuple[list[Path], dict[str, Any]]:
    kept: list[Path] = []
    dropped: list[dict[str, Any]] = []
    kept_meta: list[dict[str, Any]] = []
    for d in sorted(model_dirs, key=lambda x: str(x)):
        meta = load_pair_meta(d)
        neg = meta.get('class_neg_label_int_0')
        pos = meta.get('class_pos_label_int_1')
        if neg is None or pos is None:
            raise ValueError(f'pair_meta missing class fields in {d}')
        a, b = str(neg), str(pos)
        pair = f'{min(a, b)}|{max(a, b)}'
        be = read_training_best_epoch(d)
        if be is None:
            logger.warning(
                'Pair %s: no training/run_summary.json best_epoch under %s; keeping model',
                pair,
                d,
            )
            kept.append(d)
            kept_meta.append({'pair': pair, 'path': str(d), 'best_epoch': None})
            continue
        if be < min_best_epoch:
            logger.info(
                'Dropping pair %s: best_epoch=%d < min_best_epoch=%d (%s)',
                pair,
                be,
                min_best_epoch,
                d,
            )
            dropped.append({'pair': pair, 'path': str(d), 'best_epoch': be})
        else:
            kept.append(d)
            kept_meta.append({'pair': pair, 'path': str(d), 'best_epoch': be})
    report: dict[str, Any] = {
        'min_best_epoch': min_best_epoch,
        'best_epoch_convention': (
            '0-based index in training/run_summary.json (training_loop early-stopping checkpoint epoch)'
        ),
        'n_input': len(model_dirs),
        'n_kept': len(kept),
        'n_dropped': len(dropped),
        'dropped_pairs': dropped,
        'kept_pairs': kept_meta,
    }
    return sorted(kept), report


def filter_model_dirs_pain_pairs_only(
    model_dirs: list[Path],
    pain_class: str,
    logger: logging.Logger,
) -> tuple[list[Path], dict[str, Any]]:
    """Keep only ``binary__*`` dirs whose OvO pair includes ``pain_class`` (e.g. Paining)."""
    pain_class = str(pain_class).strip()
    kept: list[Path] = []
    skipped_meta: list[dict[str, str]] = []
    for d in sorted(model_dirs, key=lambda x: str(x)):
        meta = load_pair_meta(d)
        neg = str(meta.get('class_neg_label_int_0', ''))
        pos = str(meta.get('class_pos_label_int_1', ''))
        if pain_class not in (neg, pos):
            a, b = neg, pos
            pair = f'{min(a, b)}|{max(a, b)}'
            skipped_meta.append({'pair': pair, 'path': str(d)})
            continue
        kept.append(d)
    report: dict[str, Any] = {
        'pain_class': pain_class,
        'n_input': len(model_dirs),
        'n_kept': len(kept),
        'n_skipped_non_pain_pair': len(skipped_meta),
        'skipped_pairs': skipped_meta,
        'kept_paths': [str(x) for x in sorted(kept)],
    }
    logger.info(
        'Pain-pair subset: kept %d / %d dirs involving %r (expect 9 for C(10,2) pain rows)',
        len(kept),
        len(model_dirs),
        pain_class,
    )
    if len(kept) != 9:
        logger.warning(
            'Pain-pair count is %d (expected 9 when all pain OvO checkpoints are present)',
            len(kept),
        )
    return sorted(kept), report


def _infer_pose_version(resolved_path: str, cfg: dict[str, Any]) -> str:
    """Match ``data_loading.load_dataset`` heuristics (v1 vs v2)."""
    pose_v1_rel = Path(str(cfg['data']['pose_v1_dir']))
    pose_v2_rel = Path(str(cfg['data']['pose_v2_dir']))
    if not pose_v1_rel.is_absolute():
        pose_v1_rel = REPO_ROOT / pose_v1_rel
    if not pose_v2_rel.is_absolute():
        pose_v2_rel = REPO_ROOT / pose_v2_rel
    pfull = Path(resolved_path) if Path(resolved_path).is_absolute() else REPO_ROOT / resolved_path
    try:
        rp = pfull.resolve()
        v1root = pose_v1_rel.resolve()
        v2root = pose_v2_rel.resolve()
        if v1root in rp.parents or rp == v1root:
            return 'v1'
        if v2root in rp.parents or rp == v2root:
            return 'v2'
        s = str(rp).replace('\\', '/')
        if 'superanimal_v2' in s or '/pose/v2' in s.lower():
            return 'v2'
        if 'labeled' in s or '/pose/labeled' in s:
            return 'v1'
    except ValueError:
        pass
    return 'v2'


def _mask_rel_if_exists(raw_m: Any) -> str | None:
    if raw_m is None or (isinstance(raw_m, float) and pd.isna(raw_m)):
        return None
    m = _to_repo_relative(str(raw_m).strip()) if str(raw_m).strip() else None
    return m if m and pose_file_exists(m) else None


def _resolve_pose_row(row: pd.Series, pose_index: dict, pose_v1_rel: Path, cfg: dict[str, Any]) -> tuple[str | None, str, str | None]:
    sid = row.get('snippet_id')
    raw_pose = row.get('pose_path')
    if raw_pose is None or (isinstance(raw_pose, float) and pd.isna(raw_pose)):
        raw_pose = None
    rel_pose = _to_repo_relative(str(raw_pose).strip()) if raw_pose and str(raw_pose).strip() else None
    resolved: str | None = None
    version = 'v2'
    mask_rel: str | None = None

    if pose_index and isinstance(sid, str):
        ent = pose_index.get(sid)
        st = str(ent.get('status', '')).lower() if ent else ''
        if ent and st == 'done':
            rp = _to_repo_relative(ent.get('pose_path'))
            rm = _to_repo_relative(ent.get('pose_mask_path')) if ent.get('pose_mask_path') else None
            if rp and pose_file_exists(rp):
                resolved = rp
                version = _infer_pose_version(resolved, cfg)
                mask_rel = rm if rm and pose_file_exists(rm) else None

    if resolved is None and rel_pose and pose_file_exists(rel_pose):
        resolved = rel_pose
        version = _infer_pose_version(resolved, cfg)
        mask_rel = _mask_rel_if_exists(row.get('pose_mask_path'))
    elif resolved is None:
        if isinstance(sid, str) and sid:
            v1 = resolve_v1_pose(sid, pose_v1_rel)
            if v1 and pose_file_exists(v1):
                resolved = v1
                version = 'v1'
                v1m = pose_v1_rel / f'{sid}_pose_mask.npy'
                v1m_rel = str(v1m).replace('\\', '/')
                mask_rel = v1m_rel if pose_file_exists(v1m_rel) else _mask_rel_if_exists(row.get('pose_mask_path'))
    return resolved, version, mask_rel


def _apply_vitpose_qc(df: pd.DataFrame, cfg: dict[str, Any], logger: logging.Logger) -> pd.DataFrame:
    ddata = cfg.get('data')
    vq = ddata.get('vitpose_qc') if isinstance(ddata, dict) else None
    vq = vq if isinstance(vq, dict) else {}
    if not (vq.get('filter', False) or vq.get('attach_enrichment_columns', False)):
        return df
    from vitpose_qc import  load_vitpose_enrichment

    rel = str(vq.get('enrichment', 'src/dataset_construction/reports/vitpose_qc_enrichment.jsonl')).strip()
    enr_path = Path(rel) if Path(rel).is_absolute() else REPO_ROOT / rel
    enr = load_vitpose_enrichment(enr_path)
    if vq.get('filter', False) and not enr:
        raise FileNotFoundError(
            f"data.vitpose_qc.filter is true but enrichment is missing or empty: {enr_path}"
        )
    default_ok = bool(vq.get('default_ok_if_missing', True))
    n_before = len(df)

    if vq.get('attach_enrichment_columns', False) and enr:
        df = df.copy()

        def _e(sid) -> dict:
            return enr.get(str(sid)) or {}

        def _qok(sid) -> bool:
            if str(sid) in enr:
                return bool(_e(sid).get('vitpose_qc_ok', True))
            return default_ok

        df['vitpose_mean_conf'] = df['snippet_id'].map(lambda s: _e(s).get('mean_conf'))
        df['vitpose_y_range'] = df['snippet_id'].map(lambda s: _e(s).get('y_range'))
        df['vitpose_qc_ok'] = df['snippet_id'].map(_qok)

    if vq.get('filter', False) and enr:

        def _kept(sid) -> bool:
            r = enr.get(str(sid))
            if r is None:
                return default_ok
            return bool(r.get('vitpose_qc_ok', True))

        m = df['snippet_id'].map(_kept)
        n_drop = int((~m).sum())
        df = df.loc[m].copy()
        logger.info(
            'ViTPose QC: kept %d / %d (dropped %d) using %s; default_ok_if_missing=%s',
            len(df),
            n_before,
            n_drop,
            enr_path,
            default_ok,
        )
    return df


def load_holdout_dataset(args: argparse.Namespace, cfg: dict[str, Any], logger: logging.Logger) -> pd.DataFrame:
    """Load holdout JSONL; resolve ViTPose paths; optional audio + ViTPose QC (from cfg)."""
    holdout_path = Path(str(args.holdout_manifest)).expanduser().resolve()
    if not holdout_path.is_file():
        raise FileNotFoundError(
            f'--holdout-manifest not found (use a real JSONL path): {holdout_path}'
        )
    if holdout_path.stat().st_size == 0:
        raise ValueError(f'Holdout manifest is empty: {holdout_path}')
    with open(holdout_path, encoding='utf-8') as f:
        holdout = pd.read_json(f, lines=True)

    if 'snippet_id' not in holdout.columns:
        raise ValueError('holdout manifest must contain snippet_id')
    if 'video_id' not in holdout.columns:
        raise ValueError('holdout manifest must contain video_id')
    label_field = str(cfg['labels']['label_field'])
    if label_field not in holdout.columns:
        raise ValueError(f'holdout manifest must contain {label_field!r}')

    classes_mc = get_multiclass_class_names(cfg)
    name_to_idx = {c: i for i, c in enumerate(classes_mc)}
    binary_pain = cfg['labels']['binary_pain_class']

    holdout = holdout.drop_duplicates(subset=['snippet_id'])
    holdout['snippet_id'] = holdout['snippet_id'].astype(str)
    lab = holdout[label_field].astype(str).str.strip()
    holdout = holdout.loc[lab.isin(name_to_idx)].copy()
    holdout[label_field] = holdout[label_field].astype(str).str.strip()

    pose_index = load_pose_extraction_index(cfg)
    pose_v1_rel = Path(str(cfg['data']['pose_v1_dir']))
    if not pose_v1_rel.is_absolute():
        pose_v1_rel = REPO_ROOT / pose_v1_rel

    pose_paths: list[str | None] = []
    pose_versions: list[str] = []
    pose_masks: list[str | None] = []
    for _, row in holdout.iterrows():
        pth, ver, msk = _resolve_pose_row(row, pose_index, pose_v1_rel, cfg)
        pose_paths.append(pth)
        pose_versions.append(ver)
        pose_masks.append(msk)

    holdout = holdout.copy()
    holdout['pose_path'] = pose_paths
    holdout['pose_version'] = pose_versions
    holdout['pose_mask_path'] = pose_masks
    before_pose = len(holdout)
    holdout = holdout.loc[holdout['pose_path'].notna()].copy()
    logger.info('Holdout: %d rows with resolvable ViTPose files (%d / %d before drop)', len(holdout), len(holdout), before_pose)

    holdout = _apply_vitpose_qc(holdout, cfg, logger)

    holdout['label_int'] = holdout[label_field].map(name_to_idx)
    holdout['binary_label_int'] = (holdout[label_field] == binary_pain).astype(int)
    holdout['cat_id'] = holdout['video_id'].astype(str)

    if args.audio_confidence_filter is not None:
        conf_col = None
        if 'audio_mean_conf' in holdout.columns:
            conf_col = 'audio_mean_conf'
        elif 'audio_confidence' in holdout.columns:
            conf_col = 'audio_confidence'
        if conf_col is None:
            raise ValueError(
                'audio_confidence_filter requires audio_mean_conf or audio_confidence on holdout rows'
            )
        before = len(holdout)
        holdout = holdout[holdout[conf_col] >= args.audio_confidence_filter].copy()
        logger.info(
            'Applied audio confidence filter on %s >= %s: %d -> %d',
            conf_col, args.audio_confidence_filter, before, len(holdout),
        )

    holdout['pose_path'] = holdout['pose_path'].apply(lambda x: str(x).replace('\\', '/') if x is not None else None)
    if 'pose_mask_path' in holdout.columns:
        holdout['pose_mask_path'] = holdout['pose_mask_path'].apply(
            lambda x: str(x).replace('\\', '/') if x is not None and str(x).strip() else None
        )

    return holdout.reset_index(drop=True)


def distribution_counts(df: pd.DataFrame) -> dict[str, int]:
    return dict(Counter(df['audio_label_10'].astype(str).tolist()))


def split_holdout(df: pd.DataFrame, val_fraction: float, random_state: int, logger: logging.Logger) -> tuple[pd.DataFrame, pd.DataFrame]:
    if "audio_label_10" not in df.columns:
        raise ValueError("audio_label_10 missing for stratified split")
    if "cat_id" not in df.columns:
        raise ValueError("cat_id missing for group split")

    working = df.copy()
    working["audio_label_10"] = working["audio_label_10"].astype(str)
    split_classes = sorted(working["audio_label_10"].astype(str).unique())
    working["label_int"] = pd.Categorical(working["audio_label_10"], categories=split_classes, ordered=True).codes

    split_cfg = {
        'split': {
            'group_field': 'cat_id',
            'stratify_field': 'audio_label_10',
            'val_fraction': val_fraction,
            'random_state': random_state,
        }
    }
    meta_train, meta_val, split_msg = first_stratified_group_split(working, split_cfg)
    if split_msg is not None:
        logger.warning(f'first_stratified_group_split warning: {split_msg}')
    logger.info(f'Holdout split: train={len(meta_train)} val={len(meta_val)}')
    logger.info(f'Train class counts={distribution_counts(meta_train)}')
    logger.info(f'Val class counts={distribution_counts(meta_val)}')
    logger.info(f'Unique cats train/val={meta_train["cat_id"].nunique()}/{meta_val["cat_id"].nunique()}')
    return meta_train.reset_index(drop=True), meta_val.reset_index(drop=True)


def build_pair_specs(model_dirs: list[Path]) -> list[tuple[str, Path, dict[str, Any]]]:
    pairs: list[tuple[str, Path, dict[str, Any]]] = []
    for p in model_dirs:
        meta = load_pair_meta(p)
        neg = meta.get('class_neg_label_int_0')
        pos = meta.get('class_pos_label_int_1')
        if neg is None or pos is None:
            raise ValueError(f'pair_meta missing class fields in {p}')
        a = str(neg)
        b = str(pos)
        pair = f'{min(a, b)}|{max(a, b)}'
        pairs.append((str(pair), p, meta))
    pairs.sort(key=lambda x: x[0])
    return pairs


def build_model(model_dir: Path, cfg: dict[str, Any], device: torch.device, logger: logging.Logger) -> Any:
    ckpt = model_dir / 'training' / 'best_weights.pth'
    if not ckpt.exists():
        raise FileNotFoundError(f'missing checkpoint: {ckpt}')

    n_frames = int(cfg['data']['n_frames'])
    n_keypoints = int(cfg['data']['n_keypoints'])
    if n_keypoints != 17:
        raise ValueError(
            f'P4 pairwise checkpoints expect n_keypoints=17 (ViTPose); config has {n_keypoints}. '
            'Use model_training_v2/config_p4_pairwise.yaml.'
        )
    n_channels = int(cfg['data']['n_channels']) * 2

    model = P4PoseSTGCN(
        n_frames=n_frames,
        n_keypoints=n_keypoints,
        n_channels=n_channels,
        n_classes=2,
    ).to(device)

    blob = torch.load(ckpt, map_location=device)
    state = blob.get('model_state_dict', blob) if isinstance(blob, dict) else blob
    if not isinstance(state, dict):
        raise TypeError(f'Invalid checkpoint format: {ckpt}')
    model.load_state_dict(state, strict=True)
    model.eval()
    return model


def run_inference(model: Any, records: list[dict], cfg: dict[str, Any], batch_size: int, device: torch.device) -> tuple[list[str], np.ndarray]:
    infer_cfg = copy.deepcopy(cfg)
    infer_cfg.setdefault('training', {})['binary_only'] = True
    infer_cfg.setdefault('data', {})['pose_cache'] = {'backend': 'ram'}

    ds = PoseDataset(records, infer_cfg, is_train=False, use_kinematics=True)

    loader = DataLoader(ds, batch_size=batch_size, shuffle=False, drop_last=False, num_workers=0)
    snippet_ids: list[str] = []
    probs: list[float] = []

    with torch.no_grad():
        for batch in loader:
            pose = batch['pose'].to(device)
            mask = batch['mask'].to(device)
            logits = model(pose, mask)
            p1 = F.softmax(logits['logits_binary'], dim=1)[:, 1].detach().cpu().numpy()
            probs.extend([float(x) for x in p1])
            snippet_ids.extend([str(x) for x in batch['snippet_id']])

    return snippet_ids, np.array(probs, dtype=np.float32)


def compute_ece(y_true: np.ndarray, prob: np.ndarray, n_bins: int = 10) -> float:
    n_classes = prob.shape[1]
    n = len(y_true)
    y = y_true.astype(int)
    ece = 0.0
    for c in range(n_classes):
        ys = (y == c).astype(float)
        pc = prob[:, c]
        edges = np.linspace(0.0, 1.0, n_bins + 1)
        for b in range(n_bins):
            lo, hi = edges[b], edges[b + 1]
            if b < n_bins - 1:
                idx = (pc >= lo) & (pc < hi)
            else:
                idx = (pc >= lo) & (pc <= hi)
            if idx.sum() == 0:
                continue
            acc = ys[idx].mean()
            conf = pc[idx].mean()
            ece += (idx.sum() / n) * abs(acc - conf)
    return float(ece)


def calibration_table(prob: np.ndarray, y_true: np.ndarray, class_names: list[str], n_bins: int = 10) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    y = y_true.astype(int)
    n_classes = prob.shape[1]
    edges = np.linspace(0.0, 1.0, n_bins + 1)
    for ci, cname in enumerate(class_names):
        ys = (y == ci).astype(float)
        pc = prob[:, ci]
        for bi in range(n_bins):
            lo, hi = edges[bi], edges[bi + 1]
            if bi < n_bins - 1:
                idx = (pc >= lo) & (pc < hi)
            else:
                idx = (pc >= lo) & (pc <= hi)
            cnt = int(idx.sum())
            rows.append(
                {
                    'class': cname,
                    'bin': bi,
                    'bin_start': float(lo),
                    'bin_end': float(hi),
                    'n_samples': cnt,
                    'avg_prob': float(pc[idx].mean()) if cnt else 0.0,
                    'positive_rate': float(ys[idx].mean()) if cnt else 0.0,
                }
            )
    return pd.DataFrame(rows)

def plot_calibration_curve(curve_df: pd.DataFrame, png_path: Path, csv_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    for cname in curve_df['class'].unique():
        sub = curve_df[curve_df['class'] == cname]
        ax.plot(sub['avg_prob'].to_numpy(), sub['positive_rate'].to_numpy(), marker='o', label=cname)
    ax.plot([0, 1], [0, 1], '--', color='black')
    ax.set_xlabel('Mean predicted confidence')
    ax.set_ylabel('Empirical positive rate')
    ax.set_title('Calibration curves (OvR)')
    ax.legend(loc='lower right', fontsize=8)
    fig.tight_layout()
    fig.savefig(png_path)
    plt.close(fig)
    curve_df.to_csv(csv_path, index=False)


def build_run_specs() -> list[tuple[int, str, dict[str, Any]]]:
    runs: list[tuple[int, str, dict[str, Any]]] = []
    i = 0

    # LogReg L1/L2 — wider C range
    for c in [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]:
        runs.append((i, 'logreg_l1', {'C': c}))
        i += 1
        runs.append((i, 'logreg_l2', {'C': c}))
        i += 1

    # ElasticNet logistic via SGD (l1_ratio sweeps mixing)
    for alpha in [0.0001, 0.001, 0.01]:
        for l1_ratio in [0.15, 0.5, 0.85]:
            runs.append((i, 'elasticnet', {'alpha': alpha, 'l1_ratio': l1_ratio}))
            i += 1

    # Random forest
    for n_estim, depth in [(100, None), (200, 5), (200, 10), (500, None), (500, 15)]:
        runs.append((i, 'random_forest', {'n_estimators': n_estim, 'max_depth': depth}))
        i += 1

    # XGBoost — added deeper and slower-learning configs
    for n_estim, lr, depth in [
        (100, 0.1, 3),
        (200, 0.05, 3),
        (200, 0.1, 5),
        (100, 0.01, 3),
        (300, 0.05, 6),
        (400, 0.01, 6),
        (300, 0.1, 8),
    ]:
        runs.append((i, 'xgboost', {'n_estimators': n_estim, 'learning_rate': lr, 'max_depth': depth}))
        i += 1

    # LightGBM — added wider leaf/depth options
    for n_estim, lr, leaves in [
        (100, 0.1, 15),
        (200, 0.05, 31),
        (200, 0.1, 63),
        (300, 0.05, 63),
        (400, 0.01, 31),
    ]:
        runs.append((i, 'lightgbm', {'n_estimators': n_estim, 'learning_rate': lr, 'num_leaves': leaves}))
        i += 1

    # MLP — more architectures
    for hidden in [(64,), (128,), (256,), (128, 64), (256, 128), (64, 32), (128, 64, 32), (256, 128, 64)]:
        for alpha in [0.0001, 0.001, 0.01]:
            runs.append((i, 'mlp', {'hidden_layer_sizes': hidden, 'alpha': alpha}))
            i += 1

    # SVM RBF
    for c in [0.1, 1.0, 10.0, 100.0]:
        for gamma in ['scale', 'auto']:
            runs.append((i, 'svm_rbf', {'C': c, 'gamma': gamma}))
            i += 1

    # KNN
    for k in [3, 5, 9, 15]:
        for weights in ['uniform', 'distance']:
            runs.append((i, 'knn', {'n_neighbors': k, 'weights': weights}))
            i += 1

    # Gaussian Naive Bayes
    runs.append((i, 'gaussian_nb', {}))
    i += 1

    return runs


def build_estimator(run_family: str, params: dict[str, Any], random_state: int, n_classes: int):
    if run_family == 'logreg_l1':
        return LogisticRegression(
            penalty='l1',
            solver='saga',
            C=params['C'],
            class_weight='balanced',
            random_state=random_state,
            max_iter=2000,
            n_jobs=1,
        )
    if run_family == 'logreg_l2':
        return LogisticRegression(
            penalty='l2',
            solver='lbfgs',
            C=params['C'],
            class_weight='balanced',
            random_state=random_state,
            max_iter=2000,
            n_jobs=1,
        )
    if run_family == 'random_forest':
        return RandomForestClassifier(
            n_estimators=params['n_estimators'],
            max_depth=params['max_depth'],
            random_state=random_state,
            class_weight='balanced',
            n_jobs=_META_RF_KNN_N_JOBS,
        )
    if run_family == 'xgboost':
        if not HAS_XGB:
            return None
        if n_classes == 2:
            return XGBClassifier(
                n_estimators=params['n_estimators'],
                learning_rate=params['learning_rate'],
                max_depth=params['max_depth'],
                objective='binary:logistic',
                eval_metric='logloss',
                tree_method='hist',
                random_state=random_state,
                n_jobs=1,
            )
        return XGBClassifier(
            n_estimators=params['n_estimators'],
            learning_rate=params['learning_rate'],
            max_depth=params['max_depth'],
            objective='multi:softprob',
            num_class=n_classes,
            eval_metric='mlogloss',
            tree_method='hist',
            random_state=random_state,
            n_jobs=1,
        )
    if run_family == 'lightgbm':
        if not HAS_LGBM:
            return None
        if n_classes == 2:
            return LGBMClassifier(
                n_estimators=params['n_estimators'],
                learning_rate=params['learning_rate'],
                num_leaves=params['num_leaves'],
                objective='binary',
                class_weight='balanced',
                random_state=random_state,
                n_jobs=1,
            )
        return LGBMClassifier(
            n_estimators=params['n_estimators'],
            learning_rate=params['learning_rate'],
            num_leaves=params['num_leaves'],
            objective='multiclass',
            num_class=n_classes,
            class_weight='balanced',
            random_state=random_state,
            n_jobs=1,
        )
    if run_family == 'mlp':
        return MLPClassifier(
            hidden_layer_sizes=params['hidden_layer_sizes'],
            alpha=params['alpha'],
            max_iter=1000,
            early_stopping=True,
            validation_fraction=0.1,
            random_state=random_state,
        )
    if run_family == 'elasticnet':
        # SGDClassifier with elasticnet penalty = logistic loss + L1+L2 mixing.
        # class_weight='balanced' handled inside; n_jobs=1 for stability.
        return SGDClassifier(
            loss='modified_huber',
            penalty='elasticnet',
            alpha=params['alpha'],
            l1_ratio=params['l1_ratio'],
            class_weight='balanced',
            max_iter=2000,
            tol=1e-4,
            random_state=random_state,
            n_jobs=1,
        )
    if run_family == 'svm_rbf':
        # probability=True required for predict_proba; calibrated Platt scaling built-in.
        # class_weight='balanced' handles imbalance.
        return SVC(
            C=params['C'],
            kernel='rbf',
            gamma=params['gamma'],
            class_weight='balanced',
            probability=True,
            random_state=random_state,
        )
    if run_family == 'knn':
        return KNeighborsClassifier(
            n_neighbors=params['n_neighbors'],
            weights=params['weights'],
            metric='euclidean',
            n_jobs=_META_RF_KNN_N_JOBS,
        )
    if run_family == 'gaussian_nb':
        return GaussianNB()
    raise ValueError(f'Unknown model family {run_family}')


def _meta_train_cv_scores(
    run_family: str,
    params: dict[str, Any],
    X_train: np.ndarray,
    y_train: np.ndarray,
    train_groups: np.ndarray,
    class_names: list[str],
    n_splits: int,
    random_state: int,
    logger: logging.Logger,
) -> dict[str, float] | None:
    """N-fold CV on meta-train only; same estimators/hparams as final fit."""
    if n_splits < 2:
        return None
    labels = list(range(len(class_names)))
    use_groups = True
    try:
        splitter = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        splits = list(splitter.split(X_train, y_train, groups=train_groups))
    except ValueError as e:
        logger.warning('StratifiedGroupKFold failed (%s); using StratifiedKFold', e)
        use_groups = False
        splitter = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        splits = list(splitter.split(X_train, y_train))

    fold_macro_f1: list[float] = []
    fold_top3: list[float] = []
    fold_auc: list[float] = []
    for tr_i, va_i in splits:
        est = build_estimator(run_family, params, random_state, n_classes=len(class_names))
        if est is None:
            return None
        sw = compute_sample_weight('balanced', y=y_train[tr_i])
        fit_kwargs: dict[str, Any] = {}
        _SW_FAMILIES = {'logreg_l1', 'logreg_l2', 'elasticnet', 'random_forest', 'xgboost', 'lightgbm'}
        if run_family in _SW_FAMILIES:
            fit_kwargs['sample_weight'] = sw
        try:
            est.fit(X_train[tr_i], y_train[tr_i], **fit_kwargs)
        except TypeError:
            est.fit(X_train[tr_i], y_train[tr_i])

        y_va = y_train[va_i]
        y_pred = est.predict(X_train[va_i])
        if hasattr(est, 'predict_proba'):
            proba = est.predict_proba(X_train[va_i])
        else:
            proba = np.eye(len(class_names))[y_pred]

        fold_macro_f1.append(float(f1_score(y_va, y_pred, average='macro', zero_division=0)))
        if len(class_names) == 2:
            fold_top3.append(float(accuracy_score(y_va, y_pred)))
            try:
                fold_auc.append(
                    float(roc_auc_score(y_va, proba[:, 1])) if len(np.unique(y_va)) > 1 else float('nan')
                )
            except ValueError:
                fold_auc.append(float('nan'))
        else:
            fold_top3.append(
                float(top_k_accuracy_score(y_va, proba, k=min(3, proba.shape[1]), labels=labels))
            )
            try:
                fold_auc.append(
                    float(roc_auc_score(y_va, proba, labels=labels, multi_class='ovr', average='macro'))
                )
            except ValueError:
                fold_auc.append(float('nan'))

    def _mean_std(xs: list[float]) -> tuple[float, float]:
        arr = np.array(xs, dtype=float)
        return float(np.nanmean(arr)), float(np.nanstd(arr))

    m_f1, s_f1 = _mean_std(fold_macro_f1)
    m_t3, s_t3 = _mean_std(fold_top3)
    m_au, s_au = _mean_std(fold_auc)
    return {
        'cv_splits': float(n_splits),
        'cv_grouped': float(1.0 if use_groups else 0.0),
        'cv_macro_f1_mean': m_f1,
        'cv_macro_f1_std': s_f1,
        'cv_top3_mean': m_t3,
        'cv_top3_std': s_t3,
        'cv_auc_roc_mean': m_au,
        'cv_auc_roc_std': s_au,
    }


def evaluate_run(
    run_idx: int,
    run_family: str,
    params: dict[str, Any],
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    val_snippets: list[str],
    class_names: list[str],
    feature_cols: list[str],
    run_root: Path,
    train_sample_weight: np.ndarray | None,
    train_groups: np.ndarray | None,
    cv_splits: int,
    random_state: int,
    binary_pain_class: str,
    meta_binary_pain: bool,
    val_audio10_labels: list[str] | None,
    logger: logging.Logger,
) -> dict[str, Any]:
    estimator = build_estimator(run_family, params, random_state, n_classes=len(class_names))
    if estimator is None:
        return {}

    cv_stats: dict[str, float] | None = None
    if cv_splits >= 2:
        try:
            if train_groups is None or len(train_groups) != len(X_train):
                raise ValueError('train_groups missing or wrong length for CV')
            cv_stats = _meta_train_cv_scores(
                run_family=run_family,
                params=params,
                X_train=X_train,
                y_train=y_train,
                train_groups=train_groups,
                class_names=class_names,
                n_splits=cv_splits,
                random_state=random_state,
                logger=logger,
            )
        except Exception as e:
            logger.warning('Meta-train CV skipped for run %d (%s): %s', run_idx, run_family, e)

    rdir = run_root / f'run_{run_idx:02d}'
    rdir.mkdir(exist_ok=True)

    _SW_FAMILIES = {'logreg_l1', 'logreg_l2', 'elasticnet', 'random_forest', 'xgboost', 'lightgbm'}
    fit_kwargs = {}
    if train_sample_weight is not None and run_family in _SW_FAMILIES:
        fit_kwargs['sample_weight'] = train_sample_weight
    try:
        estimator.fit(X_train, y_train, **fit_kwargs)
    except TypeError:
        estimator.fit(X_train, y_train)
    y_pred = estimator.predict(X_val)
    if hasattr(estimator, 'predict_proba'):
        proba = estimator.predict_proba(X_val)
    else:
        logger.warning(f'Run {run_idx} ({run_family}) has no predict_proba; using one-hot fallback')
        proba = np.eye(len(class_names))[y_pred]

    labels = list(range(len(class_names)))
    val_accuracy = float(accuracy_score(y_val, y_pred))
    val_macro_f1 = float(f1_score(y_val, y_pred, average='macro', zero_division=0))
    val_weighted_f1 = float(f1_score(y_val, y_pred, average='weighted', zero_division=0))
    val_precision = float(precision_score(y_val, y_pred, average='macro', zero_division=0))
    val_recall = float(recall_score(y_val, y_pred, average='macro', zero_division=0))
    f1_by_class = f1_score(y_val, y_pred, average=None, labels=labels, zero_division=0)
    if len(class_names) == 2:
        val_top3 = val_accuracy
        try:
            val_auc = float(roc_auc_score(y_val, proba[:, 1])) if len(np.unique(y_val)) > 1 else float('nan')
        except ValueError:
            val_auc = float('nan')
    else:
        val_top3 = float(top_k_accuracy_score(y_val, proba, k=min(3, proba.shape[1]), labels=labels))
        try:
            val_auc = float(roc_auc_score(y_val, proba, labels=labels, multi_class='ovr', average='macro'))
        except ValueError:
            val_auc = float('nan')

    val_ece = compute_ece(y_val, proba, n_bins=10)

    cm = confusion_matrix(y_val, y_pred, labels=labels)

    pain_class = str(binary_pain_class).strip()
    val_binary_f1_pain = float('nan')
    val_binary_precision_pain = float('nan')
    val_binary_recall_pain = float('nan')
    val_binary_accuracy = float('nan')
    val_binary_auc_roc = float('nan')
    if meta_binary_pain:
        val_binary_f1_pain = float(f1_score(y_val, y_pred, average='binary', pos_label=1, zero_division=0))
        val_binary_precision_pain = float(
            precision_score(y_val, y_pred, average='binary', pos_label=1, zero_division=0)
        )
        val_binary_recall_pain = float(recall_score(y_val, y_pred, average='binary', pos_label=1, zero_division=0))
        val_binary_accuracy = val_accuracy
        val_binary_auc_roc = val_auc
    elif pain_class in class_names:
        pi = int(class_names.index(pain_class))
        y_true_bin = (y_val == pi).astype(int)
        y_pred_bin = (y_pred == pi).astype(int)
        val_binary_f1_pain = float(f1_score(y_true_bin, y_pred_bin, average='binary', pos_label=1, zero_division=0))
        val_binary_precision_pain = float(
            precision_score(y_true_bin, y_pred_bin, average='binary', pos_label=1, zero_division=0)
        )
        val_binary_recall_pain = float(recall_score(y_true_bin, y_pred_bin, average='binary', pos_label=1, zero_division=0))
        val_binary_accuracy = float(accuracy_score(y_true_bin, y_pred_bin))
        try:
            if len(np.unique(y_true_bin)) > 1:
                val_binary_auc_roc = float(roc_auc_score(y_true_bin, proba[:, pi]))
        except ValueError:
            pass
    else:
        logger.warning('binary_pain_class %r not in meta class_names; skipping binary metrics', pain_class)

    row = {
        'run_index': run_idx,
        'model_family': run_family,
        'hyperparams': json.dumps(params, sort_keys=True),
        'cv_splits': int(cv_splits),
        'cv_grouped': float('nan'),
        'cv_macro_f1_mean': float('nan'),
        'cv_macro_f1_std': float('nan'),
        'cv_top3_mean': float('nan'),
        'cv_top3_std': float('nan'),
        'cv_auc_roc_mean': float('nan'),
        'cv_auc_roc_std': float('nan'),
        'val_accuracy': val_accuracy,
        'val_macro_f1': val_macro_f1,
        'val_weighted_f1': val_weighted_f1,
        'val_precision_macro': val_precision,
        'val_recall_macro': val_recall,
        'val_top3_accuracy': val_top3,
        'val_auc_roc': val_auc,
        'val_ece': val_ece,
        'val_binary_f1_pain': val_binary_f1_pain,
        'val_binary_precision_pain': val_binary_precision_pain,
        'val_binary_recall_pain': val_binary_recall_pain,
        'val_binary_accuracy': val_binary_accuracy,
        'val_binary_auc_roc': val_binary_auc_roc,
    }
    if cv_stats:
        row['cv_grouped'] = cv_stats['cv_grouped']
        row['cv_macro_f1_mean'] = cv_stats['cv_macro_f1_mean']
        row['cv_macro_f1_std'] = cv_stats['cv_macro_f1_std']
        row['cv_top3_mean'] = cv_stats['cv_top3_mean']
        row['cv_top3_std'] = cv_stats['cv_top3_std']
        row['cv_auc_roc_mean'] = cv_stats['cv_auc_roc_mean']
        row['cv_auc_roc_std'] = cv_stats['cv_auc_roc_std']
    for j, cname in enumerate(class_names):
        row[f'val_f1_{cname}'] = float(f1_by_class[j])

    with open(rdir / 'run_config.json', 'w') as f:
        json.dump(
            {
                'run_index': run_idx,
                'model_family': run_family,
                'hyperparams': params,
                'cv_splits': cv_splits,
                'cv_on_meta_train_only': bool(cv_splits >= 2),
                'binary_pain_class': pain_class,
                'meta_binary_pain': bool(meta_binary_pain),
            },
            f,
            indent=2,
        )
    with open(rdir / 'val_metrics.json', 'w') as f:
        json.dump(row, f, indent=2)
    joblib.dump(estimator, rdir / 'model.pkl')

    val_prob = pd.DataFrame({'snippet_id': val_snippets})
    val_prob[feature_cols] = X_val
    val_prob['y_true_int'] = y_val
    val_prob['y_true_label'] = [class_names[int(v)] for v in y_val]
    val_prob['y_pred_int'] = y_pred
    val_prob['y_pred_label'] = [class_names[int(v)] for v in y_pred]
    if val_audio10_labels is not None:
        val_prob['y_true_audio_label_10'] = val_audio10_labels
    if meta_binary_pain:
        val_prob['y_true_is_pain'] = y_val.astype(int)
        val_prob['y_pred_is_pain'] = y_pred.astype(int)
    elif pain_class in class_names:
        pi = int(class_names.index(pain_class))
        val_prob['y_true_is_pain'] = (y_val == pi).astype(int)
        val_prob['y_pred_is_pain'] = (y_pred == pi).astype(int)
    val_prob.to_csv(rdir / 'prob_val.csv', index=False)

    fig, ax = plt.subplots(figsize=(8, 5))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    disp.plot(ax=ax, xticks_rotation=45)
    fig.tight_layout()
    fig.savefig(rdir / 'confusion_matrix.png')
    plt.close(fig)

    if run_family.startswith('logreg') or run_family == 'elasticnet':
        coef = estimator.coef_
        if coef.shape[0] == 1:
            coef_df = pd.DataFrame(
                coef.T,
                index=feature_cols,
                columns=[f'class_{class_names[1]}'],
            )
        else:
            coef_df = pd.DataFrame(coef.T, index=feature_cols, columns=[f'class_{i}' for i in class_names])
        coef_df.to_csv(rdir / 'coefficients.csv', index_label='feature')

    if run_family in ('random_forest', 'xgboost', 'lightgbm'):
        if hasattr(estimator, 'feature_importances_'):
            pd.DataFrame({'feature': feature_cols, 'importance': estimator.feature_importances_}).to_csv(
                rdir / 'feature_importances.csv',
                index=False,
            )

    cal = calibration_table(proba, y_val, class_names, n_bins=10)
    plot_calibration_curve(cal, rdir / 'calibration_curve.png', rdir / 'calibration_curve.csv')

    if cv_stats and cv_splits >= 2:
        logger.info(
            'run=%03d family=%-11s cv_macro_f1=%.4f±%.4f | macro_f1=%6.4f top3=%6.4f '
            'bin_f1_pain=%6.4f auc=%6.4f ece=%6.4f',
            run_idx,
            run_family,
            cv_stats['cv_macro_f1_mean'],
            cv_stats['cv_macro_f1_std'],
            val_macro_f1,
            val_top3,
            val_binary_f1_pain if not np.isnan(val_binary_f1_pain) else float('nan'),
            val_auc if not np.isnan(val_auc) else float('nan'),
            val_ece,
        )
    else:
        logger.info(
            'run=%03d family=%-11s macro_f1=%6.4f top3=%6.4f bin_f1_pain=%6.4f auc=%6.4f ece=%6.4f',
            run_idx,
            run_family,
            val_macro_f1,
            val_top3,
            val_binary_f1_pain if not np.isnan(val_binary_f1_pain) else float('nan'),
            val_auc if not np.isnan(val_auc) else float('nan'),
            val_ece,
        )
    return row


def write_master_results(rows: list[dict[str, Any]], out_path: Path) -> pd.DataFrame:
    if not rows:
        return pd.DataFrame()
    m = pd.DataFrame(rows)
    m = m.sort_values('val_macro_f1', ascending=False).reset_index(drop=True)
    m.to_csv(out_path, index=False)
    return m


def _read_coefficients_table(path: Path) -> pd.DataFrame:
    """Load coefficients.csv; ensure a ``feature`` column holds OvO pair names (not row indices)."""
    df = pd.read_csv(path)
    if 'feature' not in df.columns:
        if 'Unnamed: 0' in df.columns:
            df = df.rename(columns={'Unnamed: 0': 'feature'})
        else:
            df = df.rename(columns={df.columns[0]: 'feature'})
    return df


def write_report(
    run_root: Path,
    dataset_summary: dict[str, Any],
    pair_specs: list[tuple[str, Path, dict[str, Any]]],
    master: pd.DataFrame,
    class_names: list[str],
    run_dirs: dict[int, Path],
    degenerate: list[str],
    logger: logging.Logger,
) -> None:
    lines: list[str] = []
    lines.append('ST-GCN DLC stacking report')
    lines.append('========================')
    lines.append(f'Generated: {pd.Timestamp.now()}')
    lines.append('')
    lines.append('Dataset summary:')
    lines.append(f"  total={dataset_summary['total']}")
    lines.append(f"  train={dataset_summary['train']}")
    lines.append(f"  val={dataset_summary['val']}")
    lines.append(f"  class_counts={dataset_summary['class_counts']}")
    lines.append(f"  train_class_counts={dataset_summary['train_class_counts']}")
    lines.append(f"  val_class_counts={dataset_summary['val_class_counts']}")
    if dataset_summary.get('meta_binary_pain'):
        lines.append('  meta_task=binary (pain vs non-pain from audio_label_10)')
        mbct = dataset_summary.get('meta_binary_label_counts_train')
        mbcv = dataset_summary.get('meta_binary_label_counts_val')
        if mbct and mbcv:
            lines.append(f'  meta_binary_train_counts={mbct}')
            lines.append(f'  meta_binary_val_counts={mbcv}')
    pps = dataset_summary.get('pairwise_pain_subset')
    if pps:
        lines.append('')
        lines.append('Pain-pairwise base subset (--pain-pair-models-only):')
        lines.append(f"  pain_class={pps['pain_class']}")
        lines.append(f"  n_kept={pps['n_kept']} / n_input={pps['n_input']}")
    pf = dataset_summary.get('pairwise_input_filter')
    if pf:
        lines.append('')
        lines.append('Pairwise input filter (training/run_summary.json):')
        lines.append(f"  min_best_epoch={pf['min_best_epoch']}  ({pf.get('best_epoch_convention', '')})")
        lines.append(f"  n_input={pf['n_input']}  n_kept={pf['n_kept']}  n_dropped={pf['n_dropped']}")
        dropped = pf.get('dropped_pairs') or []
        if dropped:
            lines.append('  Dropped:')
            for r in dropped:
                lines.append(f"    {r['pair']}  best_epoch={r['best_epoch']}")

    n_pairs = len(pair_specs)
    lines.append('')
    lines.append(f'Pairwise models ({n_pairs}):')
    for p, pdir, _ in pair_specs:
        lines.append(f'{p}: {pdir}')

    if len(master):
        lines.append('')
        lines.append('Best run overall:')
        b = master.iloc[0]
        lines.append(f'  run_index={int(b.run_index)} family={b.model_family}')
        lines.append(f'  hyperparams={b.hyperparams}')
        for k in ['val_accuracy', 'val_macro_f1', 'val_weighted_f1', 'val_top3_accuracy', 'val_auc_roc', 'val_ece']:
            lines.append(f'  {k}={b[k]:.4f}')
        for bk in (
            'val_binary_f1_pain',
            'val_binary_precision_pain',
            'val_binary_recall_pain',
            'val_binary_accuracy',
            'val_binary_auc_roc',
        ):
            if bk in b.index and pd.notna(b[bk]):
                lines.append(f'  {bk}={float(b[bk]):.4f}')
        for c in class_names:
            lines.append(f"  val_f1_{c}={b[f'val_f1_{c}']:.4f}")

    lines.append('')
    lines.append('Best per family:')
    for fam, g in master.groupby('model_family'):
        sb = g.sort_values('val_macro_f1', ascending=False).iloc[0]
        lines.append(f'{fam}: run={int(sb.run_index)} macro_f1={sb.val_macro_f1:.4f} top3={sb.val_top3_accuracy:.4f}')

    lines.append('')
    lines.append('Family ranking (mean val_macro_f1):')
    for fam, score in master.groupby('model_family')['val_macro_f1'].mean().sort_values(ascending=False).items():
        lines.append(f'{fam}: {score:.4f}')

    # top features
    lines.append('')
    lines.append('Top-5 features from best tree-like model:')
    tree_rows = []
    for ridx, rdir in run_dirs.items():
        fp = rdir / 'feature_importances.csv'
        if fp.exists():
            t = pd.read_csv(fp)
            t['run_index'] = ridx
            t['metric'] = master.set_index('run_index').loc[ridx, 'val_macro_f1']
            tree_rows.append(t)
    if tree_rows:
        t = pd.concat(tree_rows, ignore_index=True)
        best_tree = int(t.sort_values('metric', ascending=False).iloc[0]['run_index'])
        lines.append(f'best tree-like run: {best_tree}')
        for _, r in pd.read_csv(run_dirs[best_tree] / 'feature_importances.csv').sort_values('importance', ascending=False).head().iterrows():
            lines.append(f"  {r['feature']}: {r['importance']:.6f}")
    else:
        lines.append('No feature_importances.csv found')

    lines.append('')
    lines.append('Top-5 logreg coefficients (sum abs across classes):')
    log_rows = []
    for ridx, rdir in run_dirs.items():
        fp = rdir / 'coefficients.csv'
        if fp.exists():
            c = _read_coefficients_table(fp)
            c['abs_sum'] = c.filter(like='class_').abs().sum(axis=1)
            c['run_index'] = ridx
            c['metric'] = master.set_index('run_index').loc[ridx, 'val_macro_f1']
            log_rows.append(c[['feature', 'abs_sum', 'run_index', 'metric']])
    if log_rows:
        cdf = pd.concat(log_rows, ignore_index=True)
        best_log = int(cdf.sort_values('metric', ascending=False).iloc[0]['run_index'])
        lines.append(f'best logreg-like run: {best_log}')
        best_coef = _read_coefficients_table(run_dirs[best_log] / 'coefficients.csv')
        best_coef['abs_sum'] = best_coef.filter(like='class_').abs().sum(axis=1)
        for f, v in best_coef[['feature', 'abs_sum']].sort_values('abs_sum', ascending=False).head().itertuples(index=False, name=None):
            lines.append(f'  {f}: {v:.6f}')

    lines.append('')
    lines.append('Degenerate base model warnings:')
    if degenerate:
        for w in degenerate:
            lines.append(f'  {w}')
    else:
        lines.append('  None on val set')

    with open(run_root / 'stack_report.txt', 'w') as f:
        f.write('\n'.join(lines))
    logger.info('Wrote stack_report.txt')


def build_prob_tables(
    pair_specs: list[tuple[str, Path, dict[str, Any]]],
    df: pd.DataFrame,
    cfg: dict[str, Any],
    args: argparse.Namespace,
    logger: logging.Logger,
) -> tuple[list[str], list[str], dict[str, np.ndarray], dict[str, str]]:
    records = df.to_dict('records')
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    base_snippets: list[str] | None = None
    feature_cols: list[str] = []
    prob_map: dict[str, np.ndarray] = {}
    pair_paths: dict[str, str] = {}

    pair_iter = tqdm(pair_specs, desc='Pairwise inference', unit='pair', total=len(pair_specs), dynamic_ncols=True)
    for idx, (pair, model_dir, meta) in enumerate(pair_iter, start=1):
        pair_iter.set_description(f'Pairwise inference ({idx}/{len(pair_specs)})')
        pair_iter.set_postfix(pair=pair)
        pair_paths[pair] = str(model_dir)
        model = build_model(model_dir, cfg, device, logger)
        snippets, probs = run_inference(model, records, cfg, args.batch_size, device)
        if base_snippets is None:
            base_snippets = snippets
        else:
            if snippets != base_snippets:
                raise AssertionError(f'Snippet order mismatch at pair {pair}')
        feature_cols.append(pair)
        prob_map[pair] = probs
        del model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    pair_iter.close()

    assert base_snippets is not None
    return base_snippets, feature_cols, prob_map, pair_paths


def main() -> None:
    args = parse_args()
    if int(args.cv_splits) < 1:
        raise ValueError('--cv-splits must be >= 1')
    if args.min_best_epoch is not None and args.min_best_epoch < 0:
        raise ValueError('--min-best-epoch must be >= 0')
    cfg = load_config(args.config)
    run_root = get_run_root()
    logger = configure_logger(run_root)

    with open(run_root / 'config_used.yaml', 'w') as f:
        with open(args.config, 'r') as src:
            f.write(src.read())

    log_section(logger, 'Run initialization')
    logger.info('Run root: %s', run_root)
    logger.info('Using config: %s', args.config)
    logger.info('Python executable: %s', sys.executable)
    logger.info('XGBoost import ok=%s', HAS_XGB)
    if not HAS_XGB and _XGB_IMPORT_ERR:
        logger.warning('XGBoost import failed (%s); grid will skip xgboost runs.', _XGB_IMPORT_ERR)
    logger.info('LightGBM import ok=%s', HAS_LGBM)
    if not HAS_LGBM and _LGBM_IMPORT_ERR:
        logger.warning('LightGBM import failed (%s); grid will skip lightgbm runs.', _LGBM_IMPORT_ERR)

    log_section(logger, 'Loading pairwise models')
    model_dirs = parse_model_dirs(args)
    pair_pain_report: dict[str, Any] | None = None
    if args.pain_pair_models_only:
        pain_label = str(cfg['labels']['binary_pain_class'])
        model_dirs, pair_pain_report = filter_model_dirs_pain_pairs_only(model_dirs, pain_label, logger)
        with open(run_root / 'pairwise_pain_subset.json', 'w', encoding='utf-8') as f:
            json.dump(pair_pain_report, f, indent=2)
        if len(model_dirs) < 2:
            raise ValueError(
                f'After --pain-pair-models-only, only {len(model_dirs)} model(s) remain; need >= 2'
            )
    pair_filter_report: dict[str, Any] | None = None
    if args.min_best_epoch is not None:
        model_dirs, pair_filter_report = filter_model_dirs_by_min_best_epoch(
            model_dirs, args.min_best_epoch, logger
        )
        with open(run_root / 'pairwise_input_filter.json', 'w', encoding='utf-8') as f:
            json.dump(pair_filter_report, f, indent=2)
        logger.info(
            'Early-best filter: kept %d / %d (min_best_epoch=%d); wrote pairwise_input_filter.json',
            pair_filter_report['n_kept'],
            pair_filter_report['n_input'],
            args.min_best_epoch,
        )
        if len(model_dirs) < 2:
            raise ValueError(
                f'After --min-best-epoch {args.min_best_epoch}, only {len(model_dirs)} model(s) remain; need >= 2'
            )
    pair_specs = build_pair_specs(model_dirs)
    logger.info('Stacking uses %d pairwise base models', len(pair_specs))

    log_section(logger, 'Loading holdout set')
    holdout = load_holdout_dataset(args, cfg, logger)
    logger.info(f'Loaded holdout clips={len(holdout)}')
    logger.info(f'Class distribution={distribution_counts(holdout)}')

    if args.limit is not None:
        holdout = holdout.head(args.limit).reset_index(drop=True)
        logger.info(f'Applied --limit; now {len(holdout)} clips')

    if args.dry_run:
        logger.info('Dry-run mode active: inference and training skipped')
        meta_train, meta_val = split_holdout(holdout, args.split_fraction, args.random_seed, logger)
        logger.info(f'Dry-run dataset totals: total={len(holdout)} train={len(meta_train)} val={len(meta_val)}')
        grid = build_run_specs()
        logger.info(f'Grid size={len(grid)}')
        logger.info(
            f'  --cv-splits={args.cv_splits} (meta-train CV when >1; holdout val metrics unchanged)'
        )
        logger.info(
            f'  --min-best-epoch={args.min_best_epoch}'
            if args.min_best_epoch is not None
            else '  --min-best-epoch off (all dirs after pain subset)'
        )
        logger.info(
            f'  --pain-pair-models-only (pain={cfg["labels"]["binary_pain_class"]})'
            if args.pain_pair_models_only
            else '  --pain-pair-models-only off (use all 45 OvO dirs)'
        )
        logger.info(
            f'  --meta-binary-pain (meta target = pain vs non-pain; pain={cfg["labels"]["binary_pain_class"]})'
            if args.meta_binary_pain
            else '  --meta-binary-pain off (10-way meta target)'
        )
        logger.info(f'  Base pairwise models for stack: {len(pair_specs)}')
        logger.info(f'  XGBoost enabled={HAS_XGB}')
        logger.info(f'  LightGBM enabled={HAS_LGBM}')
        return

    log_section(logger, 'Holdout split')
    meta_train_df, meta_val_df = split_holdout(holdout, args.split_fraction, args.random_seed, logger)

    log_section(logger, 'Pairwise probability stack')
    snippet_order, feature_cols, prob_map, pair_paths = build_prob_tables(pair_specs, holdout, cfg, args, logger)

    probs_df = pd.DataFrame({'snippet_id': snippet_order})
    for c in feature_cols:
        probs_df[c] = prob_map[c]

    pain_cls = str(cfg['labels']['binary_pain_class'])
    class_names_mc = sorted(holdout['audio_label_10'].astype(str).unique())
    label_to_int_mc = {c: i for i, c in enumerate(class_names_mc)}

    meta_train_by_sid = meta_train_df.set_index('snippet_id')
    meta_val_by_sid = meta_val_df.set_index('snippet_id')
    train_index = [i for i in snippet_order if i in meta_train_by_sid.index]
    val_index = [i for i in snippet_order if i in meta_val_by_sid.index]

    X_train = probs_df.set_index('snippet_id').loc[train_index, feature_cols].to_numpy(dtype=float)
    X_val = probs_df.set_index('snippet_id').loc[val_index, feature_cols].to_numpy(dtype=float)

    if args.meta_binary_pain:
        class_names = ['non_pain', pain_cls]
        y_train = (
            meta_train_by_sid.loc[train_index, 'audio_label_10'].astype(str) == pain_cls
        ).astype(np.int64).to_numpy()
        y_val = (
            meta_val_by_sid.loc[val_index, 'audio_label_10'].astype(str) == pain_cls
        ).astype(np.int64).to_numpy()
    else:
        class_names = class_names_mc
        y_train = meta_train_by_sid.loc[train_index, 'audio_label_10'].map(label_to_int_mc).to_numpy(dtype=int)
        y_val = meta_val_by_sid.loc[val_index, 'audio_label_10'].map(label_to_int_mc).to_numpy(dtype=int)
    train_groups = meta_train_by_sid.loc[train_index, 'cat_id'].astype(str).to_numpy()

    class_ids = np.unique(y_train)
    class_weights = compute_class_weight('balanced', classes=class_ids, y=y_train)
    cw_map = {int(c): float(w) for c, w in zip(class_ids, class_weights)}
    train_sample_weight = np.array([cw_map[int(y)] for y in y_train], dtype=float)

    prob_train = probs_df.set_index('snippet_id').loc[train_index].reset_index()
    prob_train['y_true_int'] = y_train
    if args.meta_binary_pain:
        prob_train['y_true_label'] = [class_names[int(v)] for v in y_train]
        prob_train['y_true_audio_label_10'] = (
            meta_train_by_sid.loc[train_index, 'audio_label_10'].astype(str).tolist()
        )
    else:
        prob_train['y_true_label'] = meta_train_by_sid.loc[train_index, 'audio_label_10'].astype(str).tolist()

    prob_val = probs_df.set_index('snippet_id').loc[val_index].reset_index()
    prob_val['y_true_int'] = y_val
    if args.meta_binary_pain:
        prob_val['y_true_label'] = [class_names[int(v)] for v in y_val]
        prob_val['y_true_audio_label_10'] = (
            meta_val_by_sid.loc[val_index, 'audio_label_10'].astype(str).tolist()
        )
    else:
        prob_val['y_true_label'] = meta_val_by_sid.loc[val_index, 'audio_label_10'].astype(str).tolist()

    prob_train.to_csv(run_root / 'prob_train.csv', index=False)
    prob_val.to_csv(run_root / 'prob_val.csv', index=False)

    if args.meta_binary_pain:
        n_tr_pos = int(np.sum(y_train == 1))
        n_tr_neg = int(np.sum(y_train == 0))
        n_va_pos = int(np.sum(y_val == 1))
        n_va_neg = int(np.sum(y_val == 0))
        logger.info(
            'Binary meta target (%r): meta-train pain=%d non_pain=%d | meta-val pain=%d non_pain=%d',
            pain_cls,
            n_tr_pos,
            n_tr_neg,
            n_va_pos,
            n_va_neg,
        )
        if n_va_pos < 15:
            logger.warning(
                'Meta-val has only %d pain-positive clips; F1/precision/recall at the default '
                '0.5 threshold are unreliable at this scale — treat val_auc_roc as primary and use '
                'prob_val.csv (y_true_audio_label_10 + predict_proba) for post-hoc threshold sweeps.',
                n_va_pos,
            )

    degenerate_pairs = []
    for c in feature_cols:
        m = float(prob_val[c].mean())
        if m > 0.85 or m < 0.15:
            degenerate_pairs.append(f'{c}: mean(P(pos))={m:.4f}')

    runs = build_run_specs()
    logger.info(
        'Planned grid runs=%d; meta-train CV folds=%d (grouped by cat_id when possible)',
        len(runs),
        int(args.cv_splits),
    )

    rows: list[dict[str, Any]] = []
    run_dirs: dict[int, Path] = {}

    active_runs = [
        (run_idx, fam, params)
        for run_idx, fam, params in runs
        if not (
            (fam == 'xgboost' and not HAS_XGB) or
            (fam == 'lightgbm' and not HAS_LGBM)
        )
    ]
    skipped = len(runs) - len(active_runs)
    if skipped:
        logger.warning('Skipping %d run(s) because optional dependencies are missing', skipped)

    log_section(logger, 'Meta-learner grid search')
    run_iter = tqdm(active_runs, desc='Meta-learner grid', unit='run', total=len(active_runs), dynamic_ncols=True)
    for step, (run_idx, fam, params) in enumerate(run_iter, start=1):
        run_iter.set_postfix(family=fam)
        run_iter.set_description(f'Run {step}/{len(active_runs)}')
        row = evaluate_run(
            run_idx=run_idx,
            run_family=fam,
            params=params,
            X_train=X_train,
            y_train=y_train,
            X_val=X_val,
            y_val=y_val,
            val_snippets=val_index,
            class_names=class_names,
            feature_cols=feature_cols,
            run_root=run_root,
            train_sample_weight=train_sample_weight,
            train_groups=train_groups,
            cv_splits=int(args.cv_splits),
            random_state=args.random_seed,
            binary_pain_class=pain_cls,
            meta_binary_pain=bool(args.meta_binary_pain),
            val_audio10_labels=(
                meta_val_by_sid.loc[val_index, 'audio_label_10'].astype(str).tolist()
                if args.meta_binary_pain
                else None
            ),
            logger=logger,
        )
        if row:
            rows.append(row)
            run_dirs[run_idx] = run_root / f'run_{run_idx:02d}'
    run_iter.close()

    master = write_master_results(rows, run_root / 'master_results.csv')
    if len(master):
        log_section(logger, 'Final ranked runs')
        if int(args.cv_splits) >= 2 and 'cv_macro_f1_mean' in master.columns:
            ranked_cols = [
                'run_index',
                'model_family',
                'cv_macro_f1_mean',
                'cv_macro_f1_std',
                'val_macro_f1',
                'val_top3_accuracy',
                'val_auc_roc',
            ]
            if 'val_binary_f1_pain' in master.columns:
                ranked_cols.append('val_binary_f1_pain')
            if 'val_binary_auc_roc' in master.columns:
                ranked_cols.append('val_binary_auc_roc')
            ranked = master[ranked_cols].sort_values('val_macro_f1', ascending=False)
        else:
            ranked_cols = [
                'run_index',
                'model_family',
                'val_macro_f1',
                'val_top3_accuracy',
                'val_auc_roc',
            ]
            if 'val_binary_f1_pain' in master.columns:
                ranked_cols.append('val_binary_f1_pain')
            if 'val_binary_auc_roc' in master.columns:
                ranked_cols.append('val_binary_auc_roc')
            ranked = master[ranked_cols].sort_values('val_macro_f1', ascending=False)
        logger.info('\n%s', ranked.to_string(index=False))
        print(ranked.to_string(index=False))

    dataset_summary: dict[str, Any] = {
        'total': len(holdout),
        'train': len(meta_train_df),
        'val': len(meta_val_df),
        'class_counts': distribution_counts(holdout),
        'train_class_counts': distribution_counts(meta_train_df),
        'val_class_counts': distribution_counts(meta_val_df),
        'pairwise_pain_subset': pair_pain_report,
        'pairwise_input_filter': pair_filter_report,
        'n_base_pairwise_models': len(pair_specs),
        'binary_pain_class': pain_cls,
        'meta_binary_pain': bool(args.meta_binary_pain),
    }
    if args.meta_binary_pain:
        dataset_summary['meta_binary_label_counts_train'] = {
            'non_pain': int(np.sum(y_train == 0)),
            pain_cls: int(np.sum(y_train == 1)),
        }
        dataset_summary['meta_binary_label_counts_val'] = {
            'non_pain': int(np.sum(y_val == 0)),
            pain_cls: int(np.sum(y_val == 1)),
        }

    write_report(
        run_root=run_root,
        dataset_summary=dataset_summary,
        pair_specs=pair_specs,
        master=master,
        class_names=class_names,
        run_dirs=run_dirs,
        degenerate=degenerate_pairs,
        logger=logger,
    )


if __name__ == '__main__':
    main()
